name: Development Build - Linux
env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited]
  push:
    paths-ignore:
      - "README.md"
      - ".gitignore"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: '0'

      - name: Gradle Build and Test
        run: |
          ./gradlew build test --info --stacktrace
