name: Release - Linux
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  IS_SNAPSHOT: ${{ github.ref_name != 'main' }}
on:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches:
      - 'develop'
      - '!main'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Exits if invoked with tag but not from main
        if: ${{ github.ref_name != 'main' &&  github.event_name == 'tags' }}
        run: exit -1

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: '0'

      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Gradle Build and Test
        run: |
          ./gradlew build test --info --stacktrace

      - name: Prepare PGP Keyring file
        env:
          GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
        run: |
          echo "${GPG_KEY_CONTENTS}" | base64 -d > signing-key.gpg
        shell: bash

      - name: Publish to MavenCentral
        run: |
          ./gradlew publishReleasePublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository --info --stacktrace -Psnapshot=${{ env.IS_SNAPSHOT }}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
